version: "3.8"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - LOG_LEVEL=debug
      - WEBSOCKET_ENABLED:true
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=FUxb8pyStRSmitS3vy

    labels:
      - traefik.enable=true
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - traefik.http.routers.vaultwarden.rule=Host(`Domain.com`)
      - traefik.http.routers.vaultwarden.service=vaultwarden
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt

    volumes:
      - 'vaultwarden-data-fix:/data'

    networks:
      - publish_network

networks:
  publish_network:
    external: true

volumes:
  vaultwarden-data-fix:
